### ISSUE TITLE
Event Hub or Event Grid to handle events?

### ISSUE THREAD

**Issue by jzhouw** [Azure-Samples/media-services-v3-dotnet#22]
AMS v3 documents Event Grid and not mention Event Hub
https://docs.microsoft.com/en-us/azure/media-services/latest/reacting-to-media-services-events

But the sample below uses Event Hub to handle the event of live stream. Is there any reason to use Event Hub over Event Grid?

https://github.com/Azure-Samples/media-services-v3-dotnet/blob/master/LiveIngest/LiveEventWithDVR/Program.cs#L164

thanks

**Comment by rdurrance** [comment]
I am also interested in which service is recommended.

**Comment by johndeu** [comment]
Event Grid is recommended. I have someone looking at the sample use of Event Hub in this case. It may have been done for simplicity. 
Normally you would just subscribe to Event Grid and push those notifications to another service like Logic Apps or Azure Functions.

**Comment by johndeu** [comment]
Looks like the samples use Event Hubs to "receive" messages from Event Grid and store them in a location that is durable for picking up at the .NET client side. 

Azure Event Grid is an eventing service for the cloud. Azure Event Hubs is one of the supported event handlers.
See this quickstart that explains using Event Hubs as the handler for events coming from Event Grid - https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-eventhub

In the sample readme.md files that use Event Hub, you will notice the section that shows how to subscribe to AMS events coming from Event Grid.  One option when creating an EventGrid subscription on any resource is to send the events directly into an Event Hub for processing and archiving optionally. Otherwise, the events are transient.

az eventgrid event-subscription create --source-resource-id $amsResourceId --name <event-subscription-name> --endpoint-type eventhub --endpoint $hubid

We are adding more examples like this that show how to listen to the events flowing via Event Grid through Event Hub. 

You could also use any other Event handler, like Azure Functions, queue storage, service bus, webhooks, or whatever makes the most sense for your application.
Read about Event handlers for Event Grid here - https://docs.microsoft.com/en-us/azure/event-grid/event-handlers
