### ISSUE TITLE
Microsoft.Azure.Management.Media is Deprecated

### ISSUE THREAD

**Issue by andyvig** [Azure-Samples/media-services-v3-dotnet#99]
### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
Download and run the sample

### Any log messages given by the failure
Nuget UI warns the Microsoft.Azure.Management.Media package is deprecated

### Expected/desired behavior
Some idea of how to migrate from Microsoft.Azure.Management.Media to Azure.Management.Media.  The nuget link sends me [here ](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/resourcemanager/Azure.ResourceManager/docs/MigrationGuide.md)which has zero details about Azure Media Services. 

### OS and Version?
Windows latest, .net6

### Versions
Latest

### Mention any other details that might be useful
I can't seem to find a single resources that notes how to migrate off of the deprecated Microsoft.Azure.Management.Media package.  If one exists please let me know! Thanks.

**Comment by xpouyat** [comment]
Hello,
The Track2 branch has some samples which have been migrated to the the new Azure.Management.Media SDK.

For example :

https://github.com/Azure-Samples/media-services-v3-dotnet/blob/track2/Assets/Program.cs
https://github.com/Azure-Samples/media-services-v3-dotnet/blob/track2/Account/CreateAccount/Program.cs
https://github.com/Azure-Samples/media-services-v3-dotnet/blob/track2/VideoEncoding/Encoding_HEVC/Program.cs
https://github.com/Azure-Samples/media-services-v3-dotnet/blob/track2/Live/LiveEventWithDVR/Program.cs

Work is not complete, that's why it is in a separate branch for now.

**Comment by johndeu** [comment]
Yes, We are actively updating the samples to track2 in the track2 branch. 
Please monitor the work ongoing in that branch. 

FYI : @giakas

**Comment by xpouyat** [comment]
All samples have been moved to the new Azure.Management.Media SDK. Main branch has been updated.
